#!/usr/bin/env python3

import pandas as pd
import os

input_dir = "counts_output"
sets = ["RBT", "WCT", "YCT"]

for set_name in sets:
    counts_file = os.path.join(input_dir, f"{set_name}_counts.tsv")
    
    if not os.path.exists(counts_file):
        print(f"Skipping {set_name}: {counts_file} not found.")
        continue
        
    print(f"Calculating heterozygosity and raw ancestry for {set_name}...")
    
    # Load the counts matrix generated by Script 2
    df = pd.read_csv(counts_file, sep="\t")
    df = df.set_index("Locus")
    
    results = {}
    
    for sample in df.columns:
        # Convert values to strings to safely handle Pandas float casting
        val_counts = df[sample].astype(str).value_counts()
        
        # Tally up valid genotypes
        count_0 = val_counts.get("0", 0) + val_counts.get("0.0", 0)  # Target species homozygous
        count_1 = val_counts.get("1", 0) + val_counts.get("1.0", 0)  # Heterozygous
        count_2 = val_counts.get("2", 0) + val_counts.get("2.0", 0)  # Alternate species homozygous
        
        total_sites = count_0 + count_1 + count_2
        
        if total_sites == 0:
            results[sample] = {"Heterozygosity": "NA", "Raw_Ancestry": "NA"}
        else:
            # Interspecific Heterozygosity
            het = count_1 / total_sites
            
            # FIXED: Raw Ancestry Proportion = (2 * Hom_Target + Het) / (2 * Total_Sites)
            # Now tallying count_0 instead of count_2
            raw_anc = ((2 * count_0) + count_1) / (2 * total_sites)
            
            results[sample] = {
                "Heterozygosity": het,
                "Raw_Ancestry": raw_anc
            }
            
    # Save the output for R
    out_file = os.path.join(input_dir, f"{set_name}_diagnostic_metrics.tsv")
    
    # Create DataFrame from the nested dictionary and save
    pd.DataFrame.from_dict(results, orient="index") \
        .to_csv(out_file, sep="\t", index_label="Sample_ID")

print("\nDone! You can now load the 'diagnostic_metrics.tsv' files into R for the triangle plot.")